name: Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  TOML_PATH: "/pyproject.toml"

on:
  push:
    branches:
      - main

jobs:
  doc:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: ${{ env.TOML_PATH }}
      - name: Install dependencies
        run: uv lock --frozen
      - name: Build reflex page
        run: uv run reflex export --frontend-only --no-zip
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Upload to Vercel
        run: |
          cd .web
          vercel --prod --yes --token $VERCEL_TOKEN