name: Deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  TOML_PATH: "/pyproject.toml"

on:
  push:
    branches:
      - dev

jobs:
  doc:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: ${{ env.TOML_PATH }}
      - name: Install dependencies
        run: uv lock --frozen
      - name: Build reflex page
        run: uv run reflex export --frontend-only --no-zip
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Add vercel.json for static deployment
        run: |
          cat > .web/build/client/vercel.json << 'EOF'
          {
            "version": 2,
            "builds": [
              { "src": "**/*", "use": "@vercel/static" }
            ]
          }
          EOF
      - name: Upload to Vercel
        run: |
          npx vercel --prod --yes --token $VERCEL_TOKEN --cwd .web/build/client