name: Project pipeline

on:
  push

env:
  TOML_PATH: "/pyproject.toml"

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubtuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: ${{ env.TOML_PATH }}
      - name: Install dependencies
        run: uv lock --frozen
      - name: Black check
        run: black --check . 
        